name: Build & Test

on:
  pull_request:
    branches: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-and-test:
    if: ${{ !github.event.pull_request.draft }}
    name: 'Build & Test'
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.x
            7.x
            8.x
            9.x
            10.x

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build (Debug)
        run: dotnet build -c Debug

      - name: Build (Release)
        run: dotnet build -c Release

      - name: Test (Debug)
        run: dotnet test -c Debug --no-build

      - name: Test (Release)
        run: dotnet test -c Release --no-build
